# Python CircleCI 2.0 configration file
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7

    working_directory: ~/repo

    steps:
      # step 1: get repo from github
      - checkout
      # step 2: create virtualenv and install dependancies
      - run:
          name: install dependancies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirments.txt
      - run:
          name: run tests
          command: |
              . venv/bin/activate
              flake8 --exclude=venv* --statistics
              pytest -v --cov=caculator